# @package _global_

task:
  name: describe_textual_clues
  command: describe-textual-clues
  set: train
  args: []
  script_folder: clue_generation
hydra:
  job:
    name: describe_textual_clues
  run:
    dir: ${oc.env:VTT_LOG_ROOT,./logs}/clue_generation/describe_textual_clues/${now:%Y%m%dT%H%M%S}
  sweep:
    dir: ${oc.env:VTT_LOG_ROOT,./logs}/clue_generation/describe_textual_clues/${now:%Y%m%dT%H%M%S}
    subdir: ${hydra.job.num}
