# @package _global_

task:
  name: preprocess
  command: preprocess
  args: []
  script_folder: preprocessing
hydra:
  job:
    name: preprocess
  run:
    dir: ${oc.env:VTT_LOG_ROOT,./logs}/preprocessing/preprocess/${now:%Y%m%dT%H%M%S}
  sweep:
    dir: ${oc.env:VTT_LOG_ROOT,./logs}/preprocessing/preprocess/${now:%Y%m%dT%H%M%S}
    subdir: ${hydra.job.num}
