defaults:
  - launcher: local_gpu
  - task: describe_figures
  - dataset: default
  - visual_descriptions: default
  - textual_descriptions: default
  - visual_query: default
  - _self_

dry_run: false
log_root: ${oc.env:VTT_LOG_ROOT,./logs}

hydra:
  job:
    chdir: false
  output_subdir: null
