name: acl_visual_tip_of_the_tongue
root: ${launcher.dataset_root}
preprocessed: ${dataset.root}/preprocessed
processed_root: ${launcher.processed_root}
pdf_dir: ${launcher.pdf_dir}
split_index: ${launcher.split_index}
clues_dir: clues
query_output: ${dataset.root}/query_collections
visual_interpretations: null
textual_interpretations: null
