#!/usr/bin/env bash
set -euo pipefail

HOST="${HOST:-127.0.0.1}"
PORT="${PORT:-8002}"
LOCAL_GPUS="${LOCAL_GPUS:-auto}"
WORKER_HOST="${WORKER_HOST:-127.0.0.1}"
ENABLE_VLM_PRELOAD="${ENABLE_VLM_PRELOAD:-true}"
MINERU_API_OUTPUT_ROOT="${MINERU_API_OUTPUT_ROOT:-data/mineru_api_output}"
MINERU_API_MAX_CONCURRENT_REQUESTS="${MINERU_API_MAX_CONCURRENT_REQUESTS:-1}"
MINERU_PROCESSING_WINDOW_SIZE="${MINERU_PROCESSING_WINDOW_SIZE:-64}"

export MINERU_API_OUTPUT_ROOT
export MINERU_API_MAX_CONCURRENT_REQUESTS
export MINERU_PROCESSING_WINDOW_SIZE

exec mineru-router \
  --host "$HOST" \
  --port "$PORT" \
  --local-gpus "$LOCAL_GPUS" \
  --worker-host "$WORKER_HOST" \
  --enable-vlm-preload "$ENABLE_VLM_PRELOAD"
