# @package _global_

defaults:
  - override /model: phi4

stage:
  name: generate_queries
  limit: null
hydra:
  job:
    name: generate_queries
  run:
    dir: ${launcher.log_root}/query_generation/generate_queries/${now:%Y%m%dT%H%M%S}
  sweep:
    dir: ${launcher.log_root}/query_generation/generate_queries/${now:%Y%m%dT%H%M%S}
    subdir: ${hydra.job.num}
